export const FORM_MANAGEMENT_PAGE_CARDS = [
  {
    key: 'dashboard',
    icon: 'pi pi-chart-bar',
    titleKey: 'preschoolScaffold.formManagement.cards.dashboard.title',
    descriptionKey: 'preschoolScaffold.formManagement.cards.dashboard.description',
    fallbackDescription: 'See overview, statistics, and quick access to key areas.',
    to: { name: 'assessment-dashboard' },
    step: 1,
    stepLabel: 'Overview',
    category: 'start',
    prerequisite: null,
  },
  {
    key: 'build',
    icon: 'pi pi-plus-circle',
    titleKey: 'preschoolScaffold.formManagement.pages.build.title',
    descriptionKey: 'preschoolScaffold.formManagement.pages.build.description',
    fallbackDescription: 'Create a new assessment form from scratch.',
    to: { name: 'dashboard-preschool-admin-forms-build' },
    step: 2,
    stepLabel: 'Create',
    category: 'workflow',
    prerequisite: null,
  },
  {
    key: 'manage',
    icon: 'pi pi-folder-open',
    titleKey: 'preschoolScaffold.formManagement.pages.manage.title',
    descriptionKey: 'preschoolScaffold.formManagement.pages.manage.description',
    fallbackDescription: 'Browse, edit, publish, and organize your forms.',
    to: { name: 'dashboard-preschool-admin-forms-manage' },
    step: 3,
    stepLabel: 'Manage',
    category: 'workflow',
    prerequisite: null,
  },
  {
    key: 'review',
    icon: 'pi pi-chart-pie',
    titleKey: 'preschoolScaffold.formManagement.pages.review.title',
    descriptionKey: 'preschoolScaffold.formManagement.pages.review.description',
    fallbackDescription: 'View submissions, generate reports, and analyze responses.',
    to: { name: 'dashboard-preschool-admin-forms-review' },
    step: 4,
    stepLabel: 'Review',
    category: 'workflow',
    prerequisite: 'Published form',
  },
]

export const FORM_MANAGEMENT_ACTION_CARDS = [
  {
    key: 'dashboard',
    group: 'overview',
    icon: 'pi pi-chart-bar',
    titleFallback: 'Dashboard',
    titleKey: 'preschoolScaffold.formManagement.cards.dashboard.title',
    descriptionKey: 'preschoolScaffold.formManagement.cards.dashboard.description',
    fallbackDescription: 'View the module overview and jump into the most important areas.',
    to: { name: 'assessment-dashboard' },
  },
  {
    key: 'forms',
    group: 'manage',
    icon: 'pi pi-folder-open',
    titleFallback: 'Forms',
    titleKey: 'preschoolScaffold.formManagement.cards.forms.title',
    descriptionKey: 'preschoolScaffold.formManagement.cards.forms.description',
    fallbackDescription: 'Review and organize the current assessment form catalog.',
    to: { name: 'assessment-form-list' },
  },
  {
    key: 'new-form',
    group: 'build',
    icon: 'pi pi-plus-circle',
    titleFallback: 'New Form',
    titleKey: 'preschoolScaffold.formManagement.cards.newForm.title',
    descriptionKey: 'preschoolScaffold.formManagement.cards.newForm.description',
    fallbackDescription: 'Create a new form for a workflow or data collection flow.',
    to: { name: 'assessment-form-create' },
  },
  {
    key: 'submissions',
    group: 'review',
    icon: 'pi pi-inbox',
    titleFallback: 'Submissions',
    titleKey: 'preschoolScaffold.formManagement.cards.submissions.title',
    descriptionKey: 'preschoolScaffold.formManagement.cards.submissions.description',
    fallbackDescription: 'Track submissions and monitor their processing status.',
    to: { name: 'assessment-submission-list' },
  },
  {
    key: 'wizard',
    group: 'build',
    icon: 'pi pi-sparkles',
    titleFallback: 'Wizard',
    titleKey: 'preschoolScaffold.formManagement.cards.wizard.title',
    descriptionKey: 'preschoolScaffold.formManagement.cards.wizard.description',
    fallbackDescription: 'Build forms step by step with guided assistance.',
    to: { name: 'assessment-wizard' },
  },
  {
    key: 'scoring',
    group: 'build',
    icon: 'pi pi-sliders-h',
    titleFallback: 'Scoring',
    titleKey: 'preschoolScaffold.formManagement.cards.scoring.title',
    descriptionKey: 'preschoolScaffold.formManagement.cards.scoring.description',
    fallbackDescription: 'Define and manage scoring rules for the active form.',
    // Routes to form list for selection; requires form ID to access scoring editor
    to: { name: 'assessment-form-list' },
  },
  {
    key: 'print-designer',
    group: 'build',
    icon: 'pi pi-print',
    titleFallback: 'Print Designer',
    titleKey: 'preschoolScaffold.formManagement.cards.printDesigner.title',
    descriptionKey: 'preschoolScaffold.formManagement.cards.printDesigner.description',
    fallbackDescription: 'Arrange print layouts and present forms cleanly.',
    // Routes to form list for selection; requires form ID to access print designer
    to: { name: 'assessment-form-list' },
  },
  {
    key: 'reports',
    group: 'review',
    icon: 'pi pi-chart-pie',
    titleFallback: 'Reports',
    titleKey: 'preschoolScaffold.formManagement.cards.reports.title',
    descriptionKey: 'preschoolScaffold.formManagement.cards.reports.description',
    fallbackDescription: 'View summary data and reports for forms.',
    to: { name: 'assessment-reports' },
  },
  {
    key: 'audit-logs',
    group: 'manage',
    icon: 'pi pi-history',
    titleFallback: 'Audit Logs',
    titleKey: 'preschoolScaffold.formManagement.cards.auditLogs.title',
    descriptionKey: 'preschoolScaffold.formManagement.cards.auditLogs.description',
    fallbackDescription: 'Review activity and the history of changes.',
    to: { name: 'assessment-audit-logs' },
  },
]

export function groupFormManagementActionCards(cards = FORM_MANAGEMENT_ACTION_CARDS) {
  return {
    manage: cards.filter((card) => card.group === 'manage'),
    build: cards.filter((card) => card.group === 'build'),
    review: cards.filter((card) => card.group === 'review'),
    overview: cards.filter((card) => card.group === 'overview'),
  }
}
