const BASE = 'formsModuleDashboard'

export const FM_HUB_SECTIONS = [
  {
    id: 'manage',
    step: 1,
    labelKey:   `${BASE}.sections.manage.label`,
    captionKey: `${BASE}.sections.manage.caption`,
    workspaceKey: `${BASE}.workspaces.manage`,
    cards: [
      {
        key:            'templates',
        icon:           'pi-file',
        accent:         'violet',
        titleKey:       `${BASE}.cards.templates.title`,
        descriptionKey: `${BASE}.cards.templates.description`,
        route:          { name: 'dashboard-preschool-admin-forms-manage' },
      },
      {
        key:            'question-bank',
        icon:           'pi-question-circle',
        accent:         'sky',
        titleKey:       `${BASE}.cards.questionBank.title`,
        descriptionKey: `${BASE}.cards.questionBank.description`,
        route:          { name: 'dashboard-preschool-admin-forms-manage' },
      },
      {
        key:            'audit-logs',
        icon:           'pi-history',
        accent:         'slate',
        titleKey:       `${BASE}.cards.auditLogs.title`,
        descriptionKey: `${BASE}.cards.auditLogs.description`,
        route:          { name: 'dashboard-preschool-admin-forms-manage' },
      },
    ],
  },
  {
    id: 'build',
    step: 2,
    labelKey:   `${BASE}.sections.build.label`,
    captionKey: `${BASE}.sections.build.caption`,
    workspaceKey: `${BASE}.workspaces.build`,
    cards: [
      {
        key:            'exercise-builder',
        icon:           'pi-clipboard',
        accent:         'emerald',
        titleKey:       `${BASE}.cards.exerciseBuilder.title`,
        descriptionKey: `${BASE}.cards.exerciseBuilder.description`,
        route:          { name: 'dashboard-preschool-admin-forms-build' },
      },
      {
        key:            'scoring-rules',
        icon:           'pi-bullseye',
        accent:         'amber',
        titleKey:       `${BASE}.cards.scoringRules.title`,
        descriptionKey: `${BASE}.cards.scoringRules.description`,
        route:          { name: 'dashboard-preschool-admin-forms-build' },
      },
      {
        key:            'print-templates',
        icon:           'pi-print',
        accent:         'teal',
        titleKey:       `${BASE}.cards.printTemplates.title`,
        descriptionKey: `${BASE}.cards.printTemplates.description`,
        route:          { name: 'dashboard-preschool-admin-forms-build' },
      },
    ],
  },
  {
    id: 'review',
    step: 3,
    labelKey:   `${BASE}.sections.review.label`,
    captionKey: `${BASE}.sections.review.caption`,
    workspaceKey: `${BASE}.workspaces.review`,
    cards: [
      {
        key:            'sessions',
        icon:           'pi-users',
        accent:         'indigo',
        titleKey:       `${BASE}.cards.sessions.title`,
        descriptionKey: `${BASE}.cards.sessions.description`,
        route:          { name: 'dashboard-preschool-admin-forms-review' },
      },
      {
        key:            'submission-review',
        icon:           'pi-check-square',
        accent:         'green',
        titleKey:       `${BASE}.cards.submissionReview.title`,
        descriptionKey: `${BASE}.cards.submissionReview.description`,
        route:          { name: 'dashboard-preschool-admin-forms-review' },
      },
      {
        key:            'export-center',
        icon:           'pi-download',
        accent:         'cyan',
        titleKey:       `${BASE}.cards.exportCenter.title`,
        descriptionKey: `${BASE}.cards.exportCenter.description`,
        route:          { name: 'dashboard-preschool-admin-forms-review' },
      },
      {
        key:            'analytics',
        icon:           'pi-chart-line',
        accent:         'rose',
        titleKey:       `${BASE}.cards.analytics.title`,
        descriptionKey: `${BASE}.cards.analytics.description`,
        route:          { name: 'dashboard-preschool-admin-forms-review' },
      },
    ],
  },
]

export const FORM_MANAGEMENT_PAGE_CARDS = [
  {
    key: 'dashboard',
    icon: 'pi pi-chart-bar',
    titleKey: 'preschoolScaffold.formManagement.cards.dashboard.title',
    descriptionKey: 'preschoolScaffold.formManagement.cards.dashboard.description',
    fallbackDescription: 'View the module overview and jump into the most important areas.',
    to: { name: 'assessment-dashboard' },
  },
  {
    key: 'manage',
    icon: 'pi pi-folder-open',
    titleKey: 'preschoolScaffold.formManagement.pages.manage.title',
    descriptionKey: 'preschoolScaffold.formManagement.pages.manage.description',
    fallbackDescription: 'Open the form catalog and related records.',
    to: { name: 'dashboard-preschool-admin-forms-manage' },
  },
  {
    key: 'build',
    icon: 'pi pi-wrench',
    titleKey: 'preschoolScaffold.formManagement.pages.build.title',
    descriptionKey: 'preschoolScaffold.formManagement.pages.build.description',
    fallbackDescription: 'Work on the tools used to create and refine forms.',
    to: { name: 'dashboard-preschool-admin-forms-build' },
  },
  {
    key: 'review',
    icon: 'pi pi-chart-pie',
    titleKey: 'preschoolScaffold.formManagement.pages.review.title',
    descriptionKey: 'preschoolScaffold.formManagement.pages.review.description',
    fallbackDescription: 'Review submission and reporting outputs.',
    to: { name: 'dashboard-preschool-admin-forms-review' },
  },
]

export const FORM_MANAGEMENT_ACTION_CARDS = [
  {
    key: 'dashboard',
    group: 'overview',
    icon: 'pi pi-chart-bar',
    titleFallback: 'Dashboard',
    titleKey: 'preschoolScaffold.formManagement.cards.dashboard.title',
    descriptionKey: 'preschoolScaffold.formManagement.cards.dashboard.description',
    fallbackDescription: 'View the module overview and jump into the most important areas.',
    to: { name: 'assessment-dashboard' },
  },
  {
    key: 'forms',
    group: 'manage',
    icon: 'pi pi-folder-open',
    titleFallback: 'Forms',
    titleKey: 'preschoolScaffold.formManagement.cards.forms.title',
    descriptionKey: 'preschoolScaffold.formManagement.cards.forms.description',
    fallbackDescription: 'Review and organize the current assessment form catalog.',
    to: { name: 'assessment-form-list' },
  },
  {
    key: 'question-bank',
    group: 'manage',
    icon: 'pi pi-question-circle',
    titleFallback: 'Question Library',
    titleKey: 'formsModuleDashboard.cards.questionBank.title',
    descriptionKey: 'formsModuleDashboard.cards.questionBank.description',
    fallbackDescription: 'Review reusable questions within the assessment template catalog.',
    to: { name: 'forms-questions' },
  },
  {
    key: 'new-form',
    group: 'build',
    icon: 'pi pi-plus-circle',
    titleFallback: 'New Form',
    titleKey: 'preschoolScaffold.formManagement.cards.newForm.title',
    descriptionKey: 'preschoolScaffold.formManagement.cards.newForm.description',
    fallbackDescription: 'Create a new form for a workflow or data collection flow.',
    to: { name: 'assessment-form-create' },
  },
  {
    key: 'submissions',
    group: 'review',
    icon: 'pi pi-inbox',
    titleFallback: 'Submissions',
    titleKey: 'preschoolScaffold.formManagement.cards.submissions.title',
    descriptionKey: 'preschoolScaffold.formManagement.cards.submissions.description',
    fallbackDescription: 'Track submissions and monitor their processing status.',
    to: { name: 'assessment-submission-list' },
  },
  {
    key: 'wizard',
    group: 'build',
    icon: 'pi pi-sparkles',
    titleFallback: 'Wizard',
    titleKey: 'preschoolScaffold.formManagement.cards.wizard.title',
    descriptionKey: 'preschoolScaffold.formManagement.cards.wizard.description',
    fallbackDescription: 'Build forms step by step with guided assistance.',
    to: { name: 'assessment-wizard' },
  },
  {
    key: 'scoring',
    group: 'build',
    icon: 'pi pi-sliders-h',
    titleFallback: 'Scoring',
    titleKey: 'preschoolScaffold.formManagement.cards.scoring.title',
    descriptionKey: 'preschoolScaffold.formManagement.cards.scoring.description',
    fallbackDescription: 'Define and manage scoring rules for the active form.',
    to: { name: 'assessment-form-list' },
  },
  {
    key: 'print-designer',
    group: 'build',
    icon: 'pi pi-print',
    titleFallback: 'Print Designer',
    titleKey: 'preschoolScaffold.formManagement.cards.printDesigner.title',
    descriptionKey: 'preschoolScaffold.formManagement.cards.printDesigner.description',
    fallbackDescription: 'Arrange print layouts and present forms cleanly.',
    to: { name: 'assessment-form-list' },
  },
  {
    key: 'reports',
    group: 'review',
    icon: 'pi pi-chart-pie',
    titleFallback: 'Reports',
    titleKey: 'preschoolScaffold.formManagement.cards.reports.title',
    descriptionKey: 'preschoolScaffold.formManagement.cards.reports.description',
    fallbackDescription: 'View summary data and reports for forms.',
    to: { name: 'assessment-reports' },
  },
  {
    key: 'audit-logs',
    group: 'manage',
    icon: 'pi pi-history',
    titleFallback: 'Audit Logs',
    titleKey: 'preschoolScaffold.formManagement.cards.auditLogs.title',
    descriptionKey: 'preschoolScaffold.formManagement.cards.auditLogs.description',
    fallbackDescription: 'Review activity and the history of changes.',
    to: { name: 'assessment-audit-logs' },
  },
]

export function groupFormManagementActionCards(cards = FORM_MANAGEMENT_ACTION_CARDS) {
  return {
    manage: cards.filter((card) => card.group === 'manage'),
    build: cards.filter((card) => card.group === 'build'),
    review: cards.filter((card) => card.group === 'review'),
    overview: cards.filter((card) => card.group === 'overview'),
  }
}
