export const REPORT_MANAGEMENT_PAGE_CARDS = [
  {
    key: 'student-reports',
    icon: 'pi pi-users',
    titleKey: 'preschoolReportsPage.cards.studentReports.title',
    titleFallback: 'Student Reports',
    descriptionKey: 'preschoolReportsPage.cards.studentReports.description',
    fallbackDescription: 'View individual student performance and assessment reports.',
    to: { name: 'dashboard-preschool-admin-student-reports' },
    step: 1,
    stepLabel: 'View',
    category: 'workflow',
    prerequisite: null,
  },
  {
    key: 'classroom-reports',
    icon: 'pi pi-sitemap',
    titleKey: 'preschoolReportsPage.cards.classroomReports.title',
    titleFallback: 'Classroom Reports',
    descriptionKey: 'preschoolReportsPage.cards.classroomReports.description',
    fallbackDescription: 'Analyze class-level performance and aggregate data.',
    to: { name: 'dashboard-preschool-admin-classroom-reports' },
    step: 2,
    stepLabel: 'Analyze',
    category: 'workflow',
    prerequisite: null,
  },
  {
    key: 'governance-review',
    icon: 'pi pi-shield',
    titleKey: 'preschoolGovernanceReviewPage.title',
    titleFallback: 'Governance Review',
    descriptionKey: 'preschoolReportsPage.cards.governanceReview.description',
    fallbackDescription: 'Review data integrity and governance issues.',
    to: { name: 'dashboard-preschool-admin-governance-review' },
    step: 3,
    stepLabel: 'Review',
    category: 'workflow',
    prerequisite: null,
  },
]

export const REPORT_MANAGEMENT_ACTION_CARDS = [
  {
    key: 'audit-logs',
    group: 'support',
    icon: 'pi pi-history',
    titleFallback: 'Audit Logs',
    titleKey: 'preschoolLifecycleAuditPage.title',
    descriptionKey: 'preschoolReportsPage.cards.auditLogs.description',
    fallbackDescription: 'Review activity and the history of changes.',
    to: { name: 'dashboard-preschool-admin-lifecycle-audit' },
  },
  {
    key: 'snapshot-archive',
    group: 'support',
    icon: 'pi pi-archive',
    titleFallback: 'Snapshot Archive',
    titleKey: 'preschoolSnapshotArchivePage.title',
    descriptionKey: 'preschoolReportsPage.cards.snapshotArchive.description',
    fallbackDescription: 'Access archived snapshots and historical data.',
    to: { name: 'dashboard-preschool-admin-report-snapshots' },
  },
  {
    key: 'governance-diff',
    group: 'governance',
    icon: 'pi pi-code',
    titleFallback: 'Diff Analysis',
    titleKey: 'preschoolGovernanceDiffPage.title',
    descriptionKey: 'preschoolReportsPage.cards.governanceDiff.description',
    fallbackDescription: 'Analyze data differences and discrepancies.',
    to: { name: 'dashboard-preschool-admin-governance-diff' },
  },
  {
    key: 'reconstruction',
    group: 'governance',
    icon: 'pi pi-refresh',
    titleFallback: 'Institutional Reconstruction',
    titleKey: 'preschoolInstitutionalReconstructionPage.title',
    descriptionKey: 'preschoolReportsPage.cards.reconstruction.description',
    fallbackDescription: 'Reconstruct and fix institutional data issues.',
    to: { name: 'dashboard-preschool-admin-reconstruction' },
  },
  {
    key: 'governance-cases',
    group: 'governance',
    icon: 'pi pi-tasks',
    titleFallback: 'Governance Cases',
    titleKey: 'preschoolGovernanceCasesPage.title',
    descriptionKey: 'preschoolReportsPage.cards.governanceCases.description',
    fallbackDescription: 'Manage governance cases and review work items.',
    to: { name: 'dashboard-preschool-admin-governance-cases' },
  },
  {
    key: 'export-governance',
    group: 'governance',
    icon: 'pi pi-download',
    titleFallback: 'Export Governance',
    titleKey: 'preschoolExportGovernancePage.title',
    descriptionKey: 'preschoolReportsPage.cards.exportGovernance.description',
    fallbackDescription: 'Export governance data and compliance reports.',
    to: { name: 'dashboard-preschool-admin-export-governance' },
  },
]

export function groupReportManagementActionCards(cards = REPORT_MANAGEMENT_ACTION_CARDS) {
  return {
    support: cards.filter((card) => card.group === 'support'),
    governance: cards.filter((card) => card.group === 'governance'),
  }
}
